context:
  version: "1.2"

package:
  name: meshoptimizer
  version: ${{ version }}

source:
  url: https://github.com/zeux/meshoptimizer/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e40f71b809cdf3361b9a4def85fd44534e8733ce29d4b943c145b76859e4c2b4

build:
  number: 0
  script:
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage('meshoptimizer', upper_bound='x.x') }}

tests:
  - package_contents:
      include:
        - meshoptimizer.h
      lib:
        - meshoptimizer
      bin:
        - meshoptdemo
  - script:
      - if: unix
        then:
          - meshoptdemo
          - cmake -S test -B test-build -G Ninja ${CMAKE_ARGS}
          - cmake --build test-build --parallel ${{ CPU_COUNT }}
          - ./test-build/test_meshoptimizer
      - if: win
        then:
          - meshoptdemo.exe
          - cmake -S test -B test-build -G Ninja %CMAKE_ARGS%
          - cmake --build test-build --parallel ${{ CPU_COUNT }}
          - .\\test-build\\test_meshoptimizer.exe
    files:
      recipe:
        - test/
    requirements:
      run:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja

about:
  homepage: https://meshoptimizer.org
  summary: Mesh optimization library that makes meshes smaller and faster to render
  description: |
    When a GPU renders triangle meshes, various stages of the GPU pipeline have to process vertex and index data.
    The efficiency of these stages depends on the data you feed to them;
    this library provides algorithms to help optimize meshes for these stages,
    as well as algorithms to reduce the mesh complexity and storage overhead.
  license: MIT
  license_file: LICENSE.md
  documentation: https://meshoptimizer.org
  repository: https://github.com/zeux/meshoptimizer

extra:
  recipe-maintainers:
    - multimeric
